Algoritmo "1 a 10 usando repita"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/10/2024
Var
// Seção de Declarações das variáveis 
c:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
c<-1
repita
      escreval(c)
      c<-c+1
ate c > 10
Fimalgoritmo