Algoritmo "1 ao 10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Eu mesmo
// Descrição   : do 1 ao 10
// Autor(a)    : Adaylson Arcanjo Evaristo
// Data atual  : 03/10/2024
Var
// Seção de Declarações das variáveis 
i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
i<-1
enquanto i <= 10 faca
         escreva(i)
         i<-i+1
fimenquanto


Fimalgoritmo