Algoritmo "numeros pares de 1 ate 50 "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Eu mesmo
// Descrição   : exibir apenas os numeros pares do 1 ate 50
// Autor(a)    : Adaylson Arcanjo Evaristo
// Data atual  : 07/10/2024
Var
// Seção de Declarações das variáveis 
c:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
c<-1
repita
      se c mod 2 = 0 entao
         escreval(c)
      fimse
      c<-c+1
ate c > 50




Fimalgoritmo