Algoritmo "soma do 1 ao 100"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Eu mesmo
// Descrição   : soma do 1 ao 100
// Autor(a)    : Adaylson Arcanjo Evaristo
// Data atual  : 03/10/2024
Var
// Seção de Declarações das variáveis 
i,t:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Bem vindo a minha função")

i<-1
t<-0
enquanto i <= 100 faca
         t<-t+i
         i<-i+1
fimenquanto
escreval(t)



Fimalgoritmo