Algoritmo "soma do 1 ate 100 usando para"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Eu mesmo
// Descrição   : somar do 1 numero ate o 100 usando para
// Autor(a)    : Adaylson Arcanjo Evaristo
// Data atual  : 08/10/2024
Var
// Seção de Declarações das variáveis 
soma,i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
soma<-0
para i de 1 ate 100 passo 1 faca
     soma<-soma+i
fimpara
escreval("A soma ficou:", soma)

Fimalgoritmo