Algoritmo "soma do 1 a 100 usando o repita"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Eu mesmo
// Descrição   : soma do 1 a 100 usando o repita
// Autor(a)    : Adaylson Arcanjo Evaristo
// Data atual  : 07/10/2024
Var
// Seção de Declarações das variáveis 
s,c:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
s<-0
c<-1
repita
      s<-c+s
      c<-c+1
ate c > 100
escreval(s)


Fimalgoritmo