Algoritmo "1 a 10 usando enquanto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Eu mesmo
// Descrição   : Fazer um laço de repetição usando o enquanto
// Autor(a)    : Adaylson Arcanjo Evaristo
// Data atual  : 23/09/2024
Var
// Seção de Declarações das variáveis 
a:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
a<-1
enquanto a < 11 faca
         escreval(a)
         a<-a+1
fimenquanto



Fimalgoritmo