Algoritmo "numeros de 1 ate 10 usando para"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Eu mesmo com exercicios
// Descrição   : Exibir 10 numeros usando para
// Autor(a)    : Adaylson Arcanjo Evaristo
// Data atual  : 25/09/2024
Var
// Seção de Declarações das variáveis 
i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para i de 1 ate 10 passo 1 faca
     escreval(i)
fimpara



Fimalgoritmo