Algoritmo "do 1 ao 10 usando o repita"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Eu
// Descrição   : do 1 ao 10 usando o repita
// Autor(a)    : Adaylson Arcanjo Evaristo
// Data atual  : 24/09/2024
Var
// Seção de Declarações das variáveis 
c:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
c<-1
repita
      escreval(c)
      c<-c+1
ate c = 11


Fimalgoritmo