Algoritmo "do 1 ao 100 usando o repita"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Eu
// Descrição   : fazer do um ao 100 usando o repita
// Autor(a)    : Adaylson Arcanjo Evaristo
// Data atual  : 24/09/2024
Var
// Seção de Declarações das variáveis 
c,s:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
c<-1
s<-0

repita
      escreval(c)
      s<-s+c
      c<-c+1
ate c = 101
escreval(s)



Fimalgoritmo