Algoritmo "pares do 1 ao 50 usando o repita"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : eu
// Descrição   : Numeros pares do 1 ao 50 usando o repita
// Autor(a)    : Adaylson Arcanjo Evaristo
// Data atual  : 24/09/2024
Var
// Seção de Declarações das variáveis 
c:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

c<-1

repita
      se c mod 2 = 0 entao
         escreval(c)
      fimse
      c<-c+1
ate c = 51



Fimalgoritmo