Algoritmo "soma do 1 ao 15"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : lista de exercicos
// Descrição   : Somar do 1 ao 15
// Autor(a)    : Adaylson Arcanjo Evaristo
// Data atual  : 18/09/2024
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval(1+2+3+4+5+6+7+8+9+10+11+12+13+14+15)



Fimalgoritmo