Algoritmo "Some do 1 ate 100 usando para"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Eu mesmo com exercicios
// Descrição   : somar do 1 ate 100 usando para
// Autor(a)    : Adaylson Arcanjo Evaristo
// Data atual  : 25/09/2024
Var
// Seção de Declarações das variáveis 
i,soma:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
soma<-0
para i de 1 ate 100 passo 1 faca
     soma<-soma+i
fimpara
escreval("A soma deu", soma)
Fimalgoritmo