Algoritmo "Treino"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Eu mesmo :)
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Adaylson Arcanjo
// Data atual  : 25/07/2024
Var
// Seção de Declarações das variáveis 
a,b :inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
a <- 10
b <- 20

a <- b
b <- 10

escreval(a, b)


Fimalgoritmo